name: Log GitHub Context and Set Environment Variables
 
on:
  push:
    branches:
      - main
      - develop
 
jobs:
  log-context:
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub Context
        run: |
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Ref: ${{ github.ref_name }}"
          echo "GitHub Event Name: ${{ github.event_name }}"
 
      - name: Set GIT_BRANCH Environment Variable
        run: |
          BRANCH_NAME=""
          if [[ "${{ github.ref_name }}" == "refs/heads/main" ]]; then
            BRANCH_NAME="main"
          elif [[ "${{ github.ref_name }}" == "refs/heads/develop" ]]; then
            BRANCH_NAME="develop"
          fi
          echo "GIT_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
 
      - name: Print GIT_BRANCH
        run: echo "GIT_BRANCH is $GIT_BRANCH"
