name: React Build & Deploy
 
on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    # START: Checkout repository and set up Node.js
    - name: Checkout Repository
      uses: actions/checkout@v3
 
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
 
    - name: Install Dependencies
      run: npm install
 
    - name: Build React App
      run: npm run build
    # END of build process
 
    # START of deployment process
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
    # END: Deployment complete
